<?php

define('LESSON_DETAIL_ATTACHMENT_TYPE_SOURCE_CODE', 1);
define('LESSON_DETAIL_ATTACHMENT_TYPE_RESOURCE', 2);
define('LESSON_DETAIL_ATTACHMENT_TYPE_SOURCE_CODE_CONTENT', 3);

define('LESSON_DETAIL_FREE_MODE_FREE', 1);
define('LESSON_DETAIL_FREE_MODE_CHARGE', 2);

define('MAIL_MODE_PENDING', 0);
define('MAIL_MODE_SENT', 1);

define('MAIL_SUBJECT_USER_ACTIVATION', 'メール認証');
define('MAIL_SUBJECT_USER_RESET_PASSWORD', 'パスワード再設定手続きのご案内');
define('MAIL_SUBJECT_CONTACT', 'お問い合わせ');

define('MEMBERSHIP_FEE', 980);

define('MODE_CREATE', 1);
define('MODE_EDIT', 2);

define('MODE_ENABLE', 1);
define('MODE_DISABLE', 0);

define('USER_MODE_ENABLE', 1);
define('USER_MODE_DISABLE', 2);

define('USER_ROLE_ADMIN', 2);
define('USER_ROLE_CLIENT', 3);
define('USER_ROLE_PUBLIC', 1);

define('USER_GRADE_NORMAL', 1);
define('USER_GRADE_DIAMOND', 2);
define('USER_GRADE_PENDING_DIAMOND', 3);

define('USER_PAYMENT_CHARGE_SUCCEEDED', 1);
define('USER_PAYMENT_CHARGE_FAILED', 2);

define('USER_LESSON_MODE_ENROLL', 1);
define('USER_LESSON_MODE_CLOSE', 2);

define('USER_LESSON_DETAIL_MODE_VIEW', 1);
define('USER_LESSON_DETAIL_MODE_LEARN', 2);
define('USER_LESSON_DETAIL_MODE_CLOSE', 3);

define('USER_UTM_A8', 1);
